### PR TITLE
Fix color of category select in order to be visible

### LINKED ISSUE #45: Bugfix: Change Color font text on select field
## Description
There is a visual error in our app "Today I Learned" when creating a new post. When you click on the "create a post" link and navigate to the blog creator page (/new/post), the selected channel category does not show visually because it is using a white color font. It would be good to change the font color to a dark blue or black to make it more visible.

### Steps to reproduce
1. Log in to the "Today I Learned" app
2. Click on the "create a post" link
3. Select a channel category
4. Observe that the selected channel is not visually apparent due to the white font color
4. Expected behavior
6. When a channel category is selected, it should be visually apparent to the user.

### Actual behavior
The selected channel is not visually apparent to the user due to the white font color.

Screen Shot 2023-01-03 at 6 59 06 PM
Screen Shot 2023-01-03 at 6 58 53 PM

### Additional Information
This issue occurs on all devices and browsers tested.

### PR DESCRIPTION
**Pull request by aldompe95**
## Quick Info
There is a visual error in our app "Today I Learned" when creating a new post. When you click on the "create a post" link and navigate to the blog creator page (/new/post), the selected channel category does not show visually because it is using a white color font.  Closes #45 

## What does this change?
Update color of font to be black

## Why are you changing that?
Because the font is not readable to the users.

## Migrations?
No

## How do you manually test this?
Manually visiting the form

## Screenshots
image

### CODE REVIEW

**Review by vicmaster — CHANGES_REQUESTED** [review]
I know that I requested this fix for post_channel select, but Im seeing that on profile developer_editor select it having the same behavior what if you aim for select type inputs? so we tackled this all at once?

**Comment by aldompe95** [comment]
@vicmaster sure on it :raised_hands:

**Comment by aldompe95** [comment]
@vicmaster fixed dev form too :smile: 

image

**Review by fabiannabi — APPROVED** [review]
lgtm

**Pull request merged**
